### ISSUE TITLE
Login fails view

### ISSUE THREAD

**Issue by BrandonLeck** [davideast/firebase-ionic-login-sample#1]
Hello friend although you install the "InAppBrowser" plugin, when I run the app on my phone and I authenticate with google, does not pass the "login" view. Why does this happen?. Thank you.

**Comment by 1dolinski** [comment]
I'm also facing this issue with firebase v3. Works properly with ionic serve, however, when running in the ios emulator and testflight the redirect and popup windows do not show. I have the latest InAppBrowser plugin installed. 

Update: 
1. switched to signInWithRedirect and then getRedirectResult
2. found that signInWithRedirect displayed a white screen, partial fix by using cordova whitelist plugin and putting  <allow-navigation href="*"/> into the config.xml (will specify the urls later) 
3. ionic serve --livereload, ionic emulate --livereload both will now display the user login window properly

Outstanding Issue: ionic emulate does not open the signInWithRedirect window at all

**Comment by abeisgoat** [comment]
@ebbflowgo Can you provide some example of how you got `signInWithRedirect` to work?

**Comment by iriekun** [comment]
Hello! How do you make it fit with firebase 3? It doesn't work with firebase 3! Can you update the code?

**Comment by geovannaterceros** [comment]
Hello, I have problem with firebase 
194275   error    TypeError: $firebaseAuth is not a function
    at Object.Auth (http://localhost:8100/js/factory.js:50:20)
    at new LoginCtrl (http://localhost:8100/js/controllers.js:96:16)

**Comment by MandelbrotMan** [comment]
I dont know the exact reason but you may need some plugins, or your firebase console may not be set up properly.
https://javebratt.com/ionic-social-login-firebase/
