### ISSUE TITLE
Bad Tutorial

### ISSUE THREAD

**Issue by swapnilagarwwal** [davideast/firebase-ionic-login-sample#3]
This is a very bad tutorial, many things are missing:
- Firebase URL
- firebase and angularfire do not get installed in lib folder
- .service('rootRef', ['FirebaseUrl', Firebase]): can't find variable firebase. 

Excuse me, but this is very poorly written tutorial.

**Comment by davideast** [comment]
Hi @agarwalswapnil,

You may be using the new Firebase SDK with this tutorial. This tutorial has not been updated to the new SDK as it does not work with social auth just yet.
